FROM node:20.15.0 AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --include=dev

ENV CYPRESS_CACHE_FOLDER=/root/.cache/Cypress

ENV CYPRESS_INSTALL_BINARY=true

RUN npx cypress install

COPY .babelrc .babelrc

COPY . .

RUN npm run build

FROM node:20.15.0 AS production

WORKDIR /app

COPY --from=build /app/.next ./.next

COPY --from=build /app/src ./src

COPY --from=build /app/src/public ./public

COPY --from=build /app/node_modules ./node_modules

COPY --from=build /app/package.json ./package.json

EXPOSE 3000

CMD ["npm", "start"]