name: CI with Docker, Jest, and Cypress

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t poweroffice-test-task -f DockerFile .

      - name: Run Next.js app in Docker
        run: docker run -d -p 3000:3000 poweroffice-test-task

      - name: Wait for Next.js to be ready
        run: npx wait-on http://localhost:3000

      - name: Run tests
        run: npm run test

      - name: Stop Next.js Docker container
        run: docker stop $(docker ps -q --filter ancestor=poweroffice-test-task)