name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_PRODUCTION }}
        run: |
          echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

      - name: Build Docker image
        run: |
          docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME_PRODUCTION }}/web -f DockerFile .

      - name: Push Docker image to Heroku
        run: |
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME_PRODUCTION }}/web

      - name: Release the app on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_PRODUCTION }}
        run: |
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME_PRODUCTION }}
