name: Deploy to heroku.

on:
  push:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          
          heroku_api_key: ${{ secrets.HEROKU_API_KEY_STAGING }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_STAGING }}


          dockerfile_directory: ./
          dockerfile_name: DockerFile

          docker_options: "--no-cache"

          process_type: web
